### ISSUE TITLE
WMS 1.3.0 not supported because of xml namespaces

### ISSUE THREAD

**Issue by tomkralidis** [geopython/OWSLib#24]
I've been debugging an owslib-using application. WMS getcapabilities doesn't work in the 1.3.0 version because of the way owslib queries the xml file with etree:

  Traceback (most recent call last):
      ...
      self.type = self._root.find('Name').text
  AttributeError: 'NoneType' object has no attribute 'find'

`self._root` is None because it is a query for `.find('Service'), which does find the service tag for 1.1.1, but in 1.3.0 it is a fully namespaced xml file. Only`.find('{http://url.to.wms.namespace/}Service')` now finds the Service tag...

I don't know if there are other changes in the 1.3.0 format, but this is at least a python-level thing that needs fixing before the actual format changes can be taken into account.

(Possible solution: some wrapper function that does the 'find' which adds the namespace? A small function to add the namespace to the string?)
