### ISSUE TITLE
WCS: creating instance fails with AttributeError

### ISSUE THREAD

**Issue by MartinPontius** [geopython/OWSLib#737]
Hi,

I use owslib version 0.22.0.

When creating a new WCS instance

```
wcs = WebCoverageService(url='http://nrt.cmems-du.eu/motu-web/wcs', 
                               version='2.0.1', 
                               auth=auth)
```

the code fails with

`AttributeError: 'WebCoverageService_2_0_1' object has no attribute 'timeout'`

Error is thrown in line 67 in wcs201.py 

` self._capabilities = reader.read(self.url, self.timeout)`

This line was changed in this merge recently: https://github.com/geopython/OWSLib/pull/730

**Comment by wildintellect** [comment]
I can confirm this bug was introduced in 0.22.0, code was working fine on 0.21.0
I think the issue is that init sets a default but the var name is timeout, it never gets assigned as part of the self object.
Fix should be adding `self.timeout = timeout` in the `_init_` of the class OR to use `timeout` not self.timeout 
`self._capabilities = reader.read(self.url, timeout)`

**Comment by tlvu** [comment]
This issue is most probably fixed by PR https://github.com/geopython/OWSLib/pull/738

**Comment by MartinPontius** [comment]
Yes, PR [738](https://github.com/geopython/OWSLib/pull/738) fixes the bug. The new release 0.23.0 is working again.
